"""
Domain models: Incident, RecoveryAction

An Incident is created when a simulated resource enters a failure state.
Recovery actions are embedded as a list within the Incident item — no separate
DynamoDB table is required for the academic scope of CloudPulse.

Design notes:
- Pure Pydantic — no AWS/DynamoDB imports here.
- RecoveryAction is an embedded value object; it is never stored independently.
- incident_id is a UUID v4 string (generated by the service layer, not here).
- All timestamps are UTC-aware datetime objects; serialised as ISO8601 strings.
- DynamoDB stores numbers as Decimal; the repository layer converts to float/int.
- None-valued optional fields are excluded when serialising to DynamoDB.
"""

from __future__ import annotations

import re
from datetime import UTC, datetime
from decimal import Decimal
from enum import Enum
from typing import Any, cast

from pydantic import BaseModel, ConfigDict, Field, computed_field, field_validator, model_validator

from app.models.resource import FailureType, ResourceState

# ── Enumerations ──────────────────────────────────────────────────────────────


class IncidentSeverity(str, Enum):
    """
    Priority level of an incident.

    Mapped from FailureType by default; may be overridden during escalation.
    - LOW       : informational, unlikely to affect users
    - MEDIUM    : degraded performance, partial impact
    - HIGH      : significant impact, recovery required promptly
    - CRITICAL  : full outage or data-integrity risk
    """

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

    def numeric(self) -> int:
        """Return a numeric rank for comparison (higher = more severe)."""
        return {"LOW": 1, "MEDIUM": 2, "HIGH": 3, "CRITICAL": 4}[self.value]


class IncidentStatus(str, Enum):
    """
    Lifecycle status of an incident.

    Valid transitions (enforced by the service layer):
        OPEN ──► RECOVERING ──► RESOLVED
          │
          └──────────────────► ESCALATED
                               (max retries exceeded or unrecoverable)

    ESCALATED and RESOLVED are terminal states.
    """

    OPEN = "OPEN"
    RECOVERING = "RECOVERING"
    RESOLVED = "RESOLVED"
    ESCALATED = "ESCALATED"

    def is_terminal(self) -> bool:
        """True if no further automatic transitions are possible."""
        return self in {IncidentStatus.RESOLVED, IncidentStatus.ESCALATED}

    def is_active(self) -> bool:
        """True if the incident requires active attention."""
        return self in {IncidentStatus.OPEN, IncidentStatus.RECOVERING}

    def can_transition_to(self, target: IncidentStatus) -> bool:
        """Check whether a status transition is allowed."""
        allowed: dict[IncidentStatus, set[IncidentStatus]] = {
            IncidentStatus.OPEN: {
                IncidentStatus.RECOVERING,
                IncidentStatus.ESCALATED,
            },
            IncidentStatus.RECOVERING: {
                IncidentStatus.RESOLVED,
                IncidentStatus.ESCALATED,
            },
            IncidentStatus.RESOLVED: set(),  # terminal
            IncidentStatus.ESCALATED: set(),  # terminal
        }
        return target in allowed.get(self, set())


class RecoveryActionType(str, Enum):
    """
    Category of automated recovery action executed during incident resolution.

    Default mapping from FailureType:
    - HIGH_CPU           -> SCALE_OUT
    - SERVICE_FAILURE    -> SERVICE_RESTART
    - STORAGE_EXHAUSTION -> STORAGE_CLEANUP
    - NETWORK_LATENCY    -> NETWORK_REROUTE
    - SERVICE_DOWNTIME   -> FAILOVER
    """

    SCALE_OUT = "SCALE_OUT"
    SERVICE_RESTART = "SERVICE_RESTART"
    STORAGE_CLEANUP = "STORAGE_CLEANUP"
    NETWORK_REROUTE = "NETWORK_REROUTE"
    FAILOVER = "FAILOVER"
    MANUAL = "MANUAL"


class RecoveryActionStatus(str, Enum):
    """Execution status of a single recovery action step."""

    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"

    def is_terminal(self) -> bool:
        return self in {RecoveryActionStatus.SUCCEEDED, RecoveryActionStatus.FAILED}


# ── Value Object: RecoveryAction ──────────────────────────────────────────────


class RecoveryAction(BaseModel):
    """
    A single automated recovery step embedded within an Incident.

    This is a value object — it has no independent existence outside an Incident.
    Stored as a DynamoDB Map inside the 'recovery_actions' List attribute.

    Validation rules:
    - action_id: non-empty UUID v4 format string
    - outcome_message: required, 1-1000 characters, stripped
    - completed_at must not precede started_at when both are present
    - error_detail must only be present when status is FAILED
    """

    # ── Identity ──────────────────────────────────────────────────────────────
    action_id: str = Field(
        ...,
        description="UUID v4 uniquely identifying this action within the incident",
        examples=["b2c3d4e5-f6a7-8901-bcde-f12345678901"],
    )

    # ── Classification ────────────────────────────────────────────────────────
    action_type: RecoveryActionType = Field(
        ...,
        description="Category of recovery action executed",
    )
    status: RecoveryActionStatus = Field(
        default=RecoveryActionStatus.PENDING,
        description="Current execution status",
    )

    # ── Timestamps ────────────────────────────────────────────────────────────
    started_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="When the action execution began",
    )
    completed_at: datetime | None = Field(
        default=None,
        description="When the action finished (success or failure)",
    )

    # ── Outcome ───────────────────────────────────────────────────────────────
    outcome_message: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="Human-readable description of what the action did",
        examples=["Simulated scale-out: increased virtual CPU allocation"],
    )
    error_detail: str | None = Field(
        default=None,
        max_length=2000,
        description="Error traceback or message; only present when status=FAILED",
    )

    # ── Validators ────────────────────────────────────────────────────────────

    @field_validator("action_id")
    @classmethod
    def validate_action_id(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("action_id must not be empty")
        if not re.fullmatch(
            r"[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}",
            v,
            re.IGNORECASE,
        ):
            raise ValueError(f"action_id must be a valid UUID v4 string, got: {v!r}")
        return v.lower()

    @field_validator("outcome_message")
    @classmethod
    def validate_outcome_message(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("outcome_message must not be empty or whitespace-only")
        return v

    @model_validator(mode="after")
    def validate_consistency(self) -> RecoveryAction:
        # completed_at must not precede started_at
        if self.completed_at is not None and self.completed_at < self.started_at:
            raise ValueError(
                "completed_at must not precede started_at: "
                f"{self.completed_at.isoformat()} < {self.started_at.isoformat()}"
            )
        # error_detail must only appear on FAILED status
        if self.error_detail is not None and self.status != RecoveryActionStatus.FAILED:
            raise ValueError(
                "error_detail must only be set when status=FAILED, "
                f"got status={self.status.value}"
            )
        return self

    # ── Domain Methods ────────────────────────────────────────────────────────

    def duration_seconds(self) -> float | None:
        """Return elapsed execution time in seconds, or None if still running."""
        if self.completed_at is None:
            return None
        return (self.completed_at - self.started_at).total_seconds()

    def to_dynamodb_map(self) -> dict[str, Any]:
        """Serialise to a DynamoDB-safe dict (excludes None and converts floats to Decimal)."""
        data = self.model_dump(mode="json")
        cleaned = {k: v for k, v in data.items() if v is not None}
        return cast(dict[str, Any], _floats_to_decimals(cleaned))

    @classmethod
    def from_dynamodb_map(cls, item: dict[str, Any]) -> RecoveryAction:
        """Deserialise from a DynamoDB Map attribute (handles Decimal)."""
        return cls.model_validate(_convert_decimals(item))


# ── Domain Model: Incident ────────────────────────────────────────────────────


# Maximum recovery actions per incident (DynamoDB 400KB item size guard)
MAX_RECOVERY_ACTIONS = 10


class Incident(BaseModel):
    """
    An incident record created when a simulated resource enters a failure state.

    Stored in the 'cloudpulse-incidents-{env}' DynamoDB table.
    RecoveryActions are embedded as a list attribute — no separate table needed.

    Validation rules:
    - incident_id: non-empty UUID v4 string
    - resource_id: non-empty, uppercase-normalised, max 64 chars
    - resolved_at / escalated_at must not precede detected_at
    - recovery_initiated_at must not precede detected_at
    - state_at_resolution must be None when status is OPEN or RECOVERING
    - RESOLVED status requires resolved_at to be set
    - ESCALATED status requires escalated_at to be set
    - recovery_attempts must equal len(recovery_actions)
    - recovery_actions may not exceed MAX_RECOVERY_ACTIONS (10)
    - duration_seconds must be >= 0 when present
    """

    # ── Identity ──────────────────────────────────────────────────────────────
    incident_id: str = Field(
        ...,
        description="UUID v4 uniquely identifying this incident",
        examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"],
    )
    resource_id: str = Field(
        ...,
        description="ID of the SimulatedResource that failed",
        examples=["VM-001"],
    )

    # ── Classification ────────────────────────────────────────────────────────
    failure_type: FailureType = Field(
        ...,
        description="Category of failure that triggered this incident",
    )
    severity: IncidentSeverity = Field(
        ...,
        description="Priority level of this incident",
    )
    status: IncidentStatus = Field(
        default=IncidentStatus.OPEN,
        description="Current lifecycle status",
    )

    # ── State Snapshots ───────────────────────────────────────────────────────
    state_at_detection: ResourceState = Field(
        ...,
        description="ResourceState of the affected resource when incident was detected",
    )
    state_at_resolution: ResourceState | None = Field(
        default=None,
        description="ResourceState when incident was resolved or escalated",
    )

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="When this incident was created in the system",
    )
    detected_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="When the failure was first detected (GSI Sort Key for all GSIs)",
    )
    recovery_started_at: datetime | None = Field(
        default=None,
        description="When automated or manual recovery started",
    )
    recovery_initiated_at: datetime | None = Field(
        default=None,
        description="When recovery was first triggered (alias for recovery_started_at)",
    )
    recovered_at: datetime | None = Field(
        default=None,
        description="When the resource reached recovered state",
    )
    resolved_at: datetime | None = Field(
        default=None,
        description="When the incident reached RESOLVED status",
    )
    escalated_at: datetime | None = Field(
        default=None,
        description="When the incident was moved to ESCALATED status",
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="When the incident record was last modified",
    )

    # ── Recovery Progress ─────────────────────────────────────────────────────
    recovery_action: str | None = Field(
        default=None,
        description="Primary recovery action applied (e.g. SCALE_OUT, SERVICE_RESTART)",
    )
    recovery_result: str | None = Field(
        default=None,
        description="Outcome of recovery (SUCCESS, FAILED, PENDING, IN_PROGRESS)",
    )
    notification_status: str = Field(
        default="NOT_SENT",
        description="Status of SNS email notifications (NOT_SENT, SENT, DELIVERED, FAILED)",
    )
    notified_transitions: list[str] = Field(
        default_factory=list,
        description="List of incident transitions for which SNS notifications were dispatched (prevents duplicates)",
    )
    retry_count: int = Field(
        default=0,
        ge=0,
        description="Number of retry attempts executed so far",
    )
    recovery_attempts: int = Field(
        default=0,
        ge=0,
        description="Number of recovery attempts executed so far",
    )
    error_message: str | None = Field(
        default=None,
        max_length=2000,
        description="Failure details or exception message if recovery failed",
    )
    recovery_actions: list[RecoveryAction] = Field(
        default_factory=list,
        description="Ordered list of recovery actions executed for this incident",
    )
    recovery_notes: list[str] = Field(
        default_factory=list,
        description="Human-readable notes appended during recovery actions",
    )

    # ── Computed / Derived ────────────────────────────────────────────────────
    duration_seconds: float | None = Field(
        default=None,
        ge=0.0,
        description=(
            "Elapsed seconds from detection to resolution. "
            "Computed and persisted on resolution. None while still open."
        ),
    )
    notification_sent: bool = Field(
        default=False,
        description="Whether an SNS notification was published for this incident",
    )

    # ── CamelCase Computed Properties for Frontend API Compatibility ──────────
    @computed_field
    def incidentId(self) -> str:
        return self.incident_id

    @computed_field
    def resourceId(self) -> str:
        return self.resource_id

    @computed_field
    def failureType(self) -> str:
        return self.failure_type.value

    @computed_field
    def createdAt(self) -> str:
        return self.created_at.isoformat()

    @computed_field
    def detectedAt(self) -> str:
        return self.detected_at.isoformat()

    @computed_field
    def recoveryStartedAt(self) -> str | None:
        val = self.recovery_started_at or self.recovery_initiated_at
        return val.isoformat() if val else None

    @computed_field
    def recoveredAt(self) -> str | None:
        val = self.recovered_at or self.resolved_at
        return val.isoformat() if val else None

    @computed_field
    def recoveryAction(self) -> str | None:
        return self.recovery_action

    @computed_field
    def recoveryResult(self) -> str | None:
        return self.recovery_result

    @computed_field
    def notificationStatus(self) -> str:
        return self.notification_status

    @computed_field
    def retryCount(self) -> int:
        return self.retry_count

    @computed_field
    def errorMessage(self) -> str | None:
        return self.error_message

    # ── Validators ────────────────────────────────────────────────────────────

    @field_validator("incident_id")
    @classmethod
    def validate_incident_id(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("incident_id must not be empty")
        if not re.fullmatch(
            r"[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}",
            v,
            re.IGNORECASE,
        ):
            raise ValueError(f"incident_id must be a valid UUID v4 string, got: {v!r}")
        return v.lower()

    @field_validator("resource_id")
    @classmethod
    def validate_resource_id(cls, v: str) -> str:
        v = v.strip().upper()
        if not v:
            raise ValueError("resource_id must not be empty")
        if len(v) > 64:
            raise ValueError("resource_id must not exceed 64 characters")
        if not re.fullmatch(r"[A-Z0-9][A-Z0-9\-]{0,63}", v):
            raise ValueError(
                f"resource_id may only contain uppercase letters, digits, and hyphens. Got: {v!r}"
            )
        return v

    @field_validator("recovery_actions")
    @classmethod
    def validate_recovery_actions_limit(cls, v: list[RecoveryAction]) -> list[RecoveryAction]:
        if len(v) > MAX_RECOVERY_ACTIONS:
            raise ValueError(
                f"recovery_actions may not exceed {MAX_RECOVERY_ACTIONS} items "
                f"per incident (DynamoDB item size guard). Got {len(v)}."
            )
        return v

    @model_validator(mode="after")
    def validate_consistency(self) -> Incident:  # noqa: C901
        """Cross-field consistency rules enforced at the domain layer."""

        # Sync timestamps and counters
        if self.recovery_initiated_at is None and self.recovery_started_at is not None:
            self.recovery_initiated_at = self.recovery_started_at
        elif self.recovery_started_at is None and self.recovery_initiated_at is not None:
            self.recovery_started_at = self.recovery_initiated_at

        if self.resolved_at is None and self.recovered_at is not None:
            self.resolved_at = self.recovered_at
        elif self.recovered_at is None and self.resolved_at is not None:
            self.recovered_at = self.resolved_at

        if self.retry_count == 0 and self.recovery_attempts > 0:
            self.retry_count = self.recovery_attempts
        elif self.recovery_attempts == 0 and self.retry_count > 0:
            self.recovery_attempts = self.retry_count

        # Default recovery_action from latest recovery action if not set
        if self.recovery_action is None and self.recovery_actions:
            self.recovery_action = self.recovery_actions[-1].action_type.value

        # Default recovery_result based on status if not set
        if self.recovery_result is None:
            if self.status == IncidentStatus.RESOLVED:
                self.recovery_result = "SUCCESS"
            elif self.status == IncidentStatus.ESCALATED:
                self.recovery_result = "FAILED"
            elif self.status == IncidentStatus.RECOVERING:
                self.recovery_result = "IN_PROGRESS"
            elif self.status == IncidentStatus.OPEN:
                self.recovery_result = "PENDING"

        # Default error_message from latest failed recovery action if not set
        if self.error_message is None and self.recovery_actions:
            latest = self.recovery_actions[-1]
            if latest.status == RecoveryActionStatus.FAILED and latest.error_detail:
                self.error_message = latest.error_detail

        # Sync notification status and boolean
        if self.notification_status == "SENT" or len(self.notified_transitions) > 0:
            self.notification_sent = True
        elif self.notification_sent and self.notification_status == "NOT_SENT":
            self.notification_status = "SENT"

        # Timestamp ordering
        effective_resolved = self.resolved_at or self.recovered_at
        if effective_resolved is not None and effective_resolved < self.detected_at:
            raise ValueError(
                "resolved_at must not precede detected_at: "
                f"{effective_resolved.isoformat()} < {self.detected_at.isoformat()}"
            )
        if self.escalated_at is not None and self.escalated_at < self.detected_at:
            raise ValueError(
                "escalated_at must not precede detected_at: "
                f"{self.escalated_at.isoformat()} < {self.detected_at.isoformat()}"
            )
        effective_recovery_start = self.recovery_initiated_at or self.recovery_started_at
        if effective_recovery_start is not None and effective_recovery_start < self.detected_at:
            raise ValueError("recovery_initiated_at must not precede detected_at")

        # state_at_resolution must be None while incident is still active
        if self.status in {IncidentStatus.OPEN, IncidentStatus.RECOVERING}:
            if self.state_at_resolution is not None:
                raise ValueError(
                    f"state_at_resolution must be None when status={self.status.value}"
                )

        # Terminal status timestamp requirements
        if self.status == IncidentStatus.RESOLVED and self.resolved_at is None and self.recovered_at is None:
            raise ValueError("resolved_at is required when status=RESOLVED")
        if self.status == IncidentStatus.ESCALATED and self.escalated_at is None:
            raise ValueError("escalated_at is required when status=ESCALATED")

        # recovery_attempts must equal number of actions logged
        if self.recovery_attempts != len(self.recovery_actions):
            raise ValueError(
                f"recovery_attempts ({self.recovery_attempts}) must equal "
                f"len(recovery_actions) ({len(self.recovery_actions)})"
            )

        return self

    # ── Domain Methods ────────────────────────────────────────────────────────

    def compute_duration_seconds(self) -> float | None:
        """
        Compute elapsed time from detection to resolution/escalation.

        Returns None while the incident is still active.
        """
        end_time = self.resolved_at or self.recovered_at
        if end_time is not None:
            return (end_time - self.detected_at).total_seconds()
        if self.escalated_at is not None:
            return (self.escalated_at - self.detected_at).total_seconds()
        return None

    def latest_action(self) -> RecoveryAction | None:
        """Return the most recently started recovery action, or None."""
        if not self.recovery_actions:
            return None
        return max(self.recovery_actions, key=lambda a: a.started_at)

    def to_dynamodb_item(self) -> dict[str, Any]:
        """Serialise to a DynamoDB-safe dict (excludes None and converts floats to Decimal)."""
        data = self.model_dump(mode="json")
        # Overwrite with correctly serialised embedded actions
        data["recovery_actions"] = [action.to_dynamodb_map() for action in self.recovery_actions]
        # Exclude computed camelCase aliases from DynamoDB to keep storage clean
        excluded_computed = {
            "incidentId", "resourceId", "failureType", "createdAt", "detectedAt",
            "recoveryStartedAt", "recoveredAt", "recoveryAction", "recoveryResult",
            "notificationStatus", "retryCount", "errorMessage"
        }
        cleaned = {k: v for k, v in data.items() if v is not None and k not in excluded_computed}
        return cast(dict[str, Any], _floats_to_decimals(cleaned))

    @classmethod
    def from_dynamodb_item(cls, item: dict[str, Any]) -> Incident:
        """Deserialise from a DynamoDB item dict (handles Decimal conversion)."""
        return cls.model_validate(_convert_decimals(item))


# ── API Response / Request Models ─────────────────────────────────────────────


class IncidentSummary(BaseModel):
    """
    Lightweight projection of an Incident for list API responses.

    Omits the full recovery_actions list to keep payload size small
    when the frontend polls the incidents list endpoint.
    Exposes both snake_case and camelCase attributes for complete frontend compatibility.
    """

    model_config = ConfigDict(populate_by_name=True)

    incident_id: str
    resource_id: str
    failure_type: FailureType
    severity: IncidentSeverity
    status: IncidentStatus
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    detected_at: datetime
    recovery_started_at: datetime | None = None
    recovered_at: datetime | None = None
    resolved_at: datetime | None = None
    escalated_at: datetime | None = None
    duration_seconds: float | None = None
    recovery_action: str | None = None
    recovery_result: str | None = None
    notification_status: str = "NOT_SENT"
    retry_count: int = 0
    recovery_attempts: int = 0
    error_message: str | None = None

    # ── Computed fields for frontend camelCase compatibility ──────────────────
    @computed_field
    def incidentId(self) -> str:
        return self.incident_id

    @computed_field
    def resourceId(self) -> str:
        return self.resource_id

    @computed_field
    def failureType(self) -> str:
        return self.failure_type.value

    @computed_field
    def createdAt(self) -> str:
        return self.created_at.isoformat()

    @computed_field
    def detectedAt(self) -> str:
        return self.detected_at.isoformat()

    @computed_field
    def recoveryStartedAt(self) -> str | None:
        val = self.recovery_started_at
        return val.isoformat() if val else None

    @computed_field
    def recoveredAt(self) -> str | None:
        val = self.recovered_at or self.resolved_at
        return val.isoformat() if val else None

    @computed_field
    def recoveryAction(self) -> str | None:
        return self.recovery_action

    @computed_field
    def recoveryResult(self) -> str | None:
        return self.recovery_result

    @computed_field
    def notificationStatus(self) -> str:
        return self.notification_status

    @computed_field
    def retryCount(self) -> int:
        return self.retry_count

    @computed_field
    def errorMessage(self) -> str | None:
        return self.error_message


class IncidentDetail(BaseModel):
    """
    Full incident representation for single-item GET /incidents/{id} responses.

    Includes the complete recovery_actions list and notes for the detail view.
    Exposes both snake_case and camelCase attributes for complete frontend compatibility.
    """

    model_config = ConfigDict(populate_by_name=True)

    incident_id: str
    resource_id: str
    failure_type: FailureType
    severity: IncidentSeverity
    status: IncidentStatus
    state_at_detection: ResourceState
    state_at_resolution: ResourceState | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    detected_at: datetime
    recovery_started_at: datetime | None = None
    recovery_initiated_at: datetime | None = None
    recovered_at: datetime | None = None
    resolved_at: datetime | None = None
    escalated_at: datetime | None = None
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    duration_seconds: float | None = None
    recovery_action: str | None = None
    recovery_result: str | None = None
    notification_status: str = "NOT_SENT"
    retry_count: int = 0
    recovery_attempts: int = 0
    error_message: str | None = None
    recovery_actions: list[RecoveryAction] = Field(default_factory=list)
    recovery_notes: list[str] = Field(default_factory=list)
    notification_sent: bool = False
    notified_transitions: list[str] = Field(default_factory=list)

    # ── Computed fields for frontend camelCase compatibility ──────────────────
    @computed_field
    def incidentId(self) -> str:
        return self.incident_id

    @computed_field
    def resourceId(self) -> str:
        return self.resource_id

    @computed_field
    def failureType(self) -> str:
        return self.failure_type.value

    @computed_field
    def createdAt(self) -> str:
        return self.created_at.isoformat()

    @computed_field
    def detectedAt(self) -> str:
        return self.detected_at.isoformat()

    @computed_field
    def recoveryStartedAt(self) -> str | None:
        val = self.recovery_started_at or self.recovery_initiated_at
        return val.isoformat() if val else None

    @computed_field
    def recoveredAt(self) -> str | None:
        val = self.recovered_at or self.resolved_at
        return val.isoformat() if val else None

    @computed_field
    def recoveryAction(self) -> str | None:
        return self.recovery_action

    @computed_field
    def recoveryResult(self) -> str | None:
        return self.recovery_result

    @computed_field
    def notificationStatus(self) -> str:
        return self.notification_status

    @computed_field
    def retryCount(self) -> int:
        return self.retry_count

    @computed_field
    def errorMessage(self) -> str | None:
        return self.error_message


# ── Internal Helpers ──────────────────────────────────────────────────────────


def _convert_decimals(obj: Any) -> Any:
    """Recursively convert DynamoDB Decimal values to int or float."""
    if isinstance(obj, Decimal):
        # Preserve integer values as int; fractional values as float
        return int(obj) if obj == obj.to_integral_value() else float(obj)
    if isinstance(obj, dict):
        return {k: _convert_decimals(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_convert_decimals(i) for i in obj]
    return obj


def _floats_to_decimals(obj: Any) -> Any:
    """Recursively convert float values to Decimal for DynamoDB serialization."""
    if isinstance(obj, float):
        return Decimal(str(obj))
    if isinstance(obj, dict):
        return {k: _floats_to_decimals(v) for k, v in obj.items() if v is not None}
    if isinstance(obj, list):
        return [_floats_to_decimals(i) for i in obj if i is not None]
    return obj
